### ISSUE TITLE
Few useful functions that can be included in the R-ecology lesson

### ISSUE THREAD

**Issue by upendrak** [datacarpentry/R-ecology-lesson#110]
In the [intro to R](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/01-intro-to-R.Rmd) I would like to introduce/add `subset` function. Here is how you can run `subset` function for the same example

> subset(animals, animals == "cat" | animals == "rat")

In the [second chapter](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/02-starting-with-data.Rmd), i also want to introduce `relevel` function 

> relevel(df, ref="WT")

**Comment by fmichonneau** [comment]
Hi @upendrak 

Thank you for your suggestions. It's a good idea to propose modifications before doing pull requests.

The data carpentry workshops are aimed at people who have no programming experience, and therefore we need to make sure we limit the number of new concepts we introduce to limit the [cognitive load](http://teaching.software-carpentry.org/11-load/). For manipulating data frames, and subsetting in particular, we favor demonstrating using `dplyr` and the `filter()` function. That's why we don't talk about `subset()` in the data frame lesson.

Similarly, we talk about factors because their behavior might be counter-intuitive when they are first encountered, and it's probably best to have a guided demonstration of their functioning during a workshop when someone can answer questions on their behavior. We currently show how to relevel factors by using the `level` argument with the `factor()` function. `relevel()` is  a convenient wrapper around this and would increase cognitive load without improving understanding.

Don't hesitate to let us know if you have other suggestions to improve the lessons.

  Thanks!
