### ISSUE TITLE
New RStudio notebook

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#127]
There's a new RStudio notebook out: http://rmarkdown.rstudio.com/r_notebooks.html

"An R Notebook is an R Markdown document with chunks that can be executed independently and interactively, with output visible immediately beneath the input."

It's still only available in Preview Release, but once it's in the standard version, it seems like it could be good for teaching. It would be interesting to hear comments if anyone gets a chance to try it out.

**Comment by tracykteal** [comment]
Blog post on its release: https://blog.rstudio.org/2016/10/05/r-notebooks/

**Comment by crazyhottommy** [comment]
I just tried it. each code chunk should only have one output (e.g. figure), otherwise, the later ones will replace the previous one. Somehow, I still like the old Rmarkdown which outputs in the console.

**Comment by tomsing1** [comment]
Actually, @crazyhottommy, I don't think that multiple outputs are a problem. I routinely generate multiple figures in a code chunk (e.g. using a for loop) and they all appear as expected. 

For example, adding a second plot to the default document that RStudio provides when a new notebook is initialized produces the attached output:
<img width="1280" alt="notebook" src="https://cloud.githubusercontent.com/assets/10490984/21745912/51cc07f6-d4ea-11e6-9b23-3dcc3404f03e.png">

On the left, in the code section, both plots are shown as thumbnails and you can flip through them. On the right, in the html output document, both plots are shown. (I am using RStudio Version 1.0.136 on Mac OS X 10.12.2.)

Generally, I use the notebooks because they allow me to update outputs from a single chunk at a time, without `knitting` the full document every time. That said, I have  run into performance issues when the document / content get's large.

I don't think that R notebooks provide a big advantage for teaching, though, as we already have the ability to run code from individual chunks and see their output in RStudio's console and Plots windows. I consider it a `nice to have` feature at this point that the learners might want to explore by themselves if they use RStudio for their analyses.

**Comment by tracykteal** [comment]
Thanks @tomsing1 & @crazyhottommy. It does seem that notebooks don't have much of an advantage for teaching right now. I'll go ahead and close this issue and we can restart or reopen if things change.
