### ISSUE TITLE
Check that the code in the challenges works as expected

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#188]
also check the solutions

- [x] Before we start
- [x] Introduction to R
- [ ] Starting with data
- [x] Aggregating and analyzing data with dplyr
- [x] Data visualization with ggplot2
- [ ] R and databases

**Comment by sdtaylor** [comment]
I'm checking these while I go thru #189 

Intro to R challenge code all works.

**Comment by sdtaylor** [comment]
In Starting with data there is a potential issue with getting the last 100 rows which I asked about [here](https://github.com/datacarpentry/R-ecology-lesson/issues/189#issuecomment-280433795). Otherwise this chapter is good.

**Comment by sdtaylor** [comment]
Data visualization with ggplot2 is good.

**Comment by sdtaylor** [comment]
In R and SQL I feel the first two challenges are a little confusing. In the first I didn't think there was a need to do a join with the species table a first, but I also didn't know the portal sqlite database also included non-rodents. So that should be explained a little earlier. 

    Challenge
    Write a query that returns the number of rodents observed in each plot in each year.

The second is also confusing, I don't think "counts of genus" means anything scientifically.  

    Challenge
    Write a query that returns counts of genus by plot_id

I made some suggestions in #199

**Comment by ha0ye** [comment]
I started going through these. The formatting in lesson 01 wasn't uniform, so I adopted the numbering format from later lessons as well as the separate blocks of {normal display of Challenge questions}, {output for code-handout}, {answers}.

**Comment by fmichonneau** [comment]
the challenges seem ok at this stage
