### ISSUE TITLE
Inclusion of conditionals in Subsetting Data in "Starting with data" lesson

### ISSUE THREAD

**Issue by dinmatias** [datacarpentry/R-ecology-lesson#192]
The use of conditionals to subset a vector was introduced in the "Introduction to R" lesson. This can be also be used to filter/subset a dataframe, which could possibly reinforce the learners mastery of conditionals -- though this might have a drawback as compared to dplyr package inwhich NAs are automatically removed.

**Comment by fmichonneau** [comment]
Thanks for this suggestion @dinmatias.

We demonstrate how to do this type of operations with dplyr rather than using the square bracket notation on data frames because it is more intuitive and it is a consistent syntax with the rest of the material. We really try to minimize the cognitive load on our learners, and showing how to do the same thing in multiple ways can be confusing when seen for the first time.
