### ISSUE TITLE
Should we recommend removing old R installations?

### ISSUE THREAD

**Issue by ha0ye** [datacarpentry/R-ecology-lesson#234]
In the lesson '00-before-we-start', it states:

> You may also want to consider removing your old version of R.

Has this actually caused problems for people? Unless having older versions of R around causes (significantly) more problems than deleting them and having to reinstall later, I'm in favor of asking people to do less and simply removing these statements from the lesson.

**Comment by fmichonneau** [comment]
I think RStudio is getting pretty good at detecting and using the latest version of R. Having multiple versions of R before the time of RStudio was confusing because there are icons for each versions, and for some learners it might have been confusing/easy to start an older version. 

I agree this sentence can be removed, unless someone can point out to issues that may arise if there are multiple versions.

**Comment by fmichonneau** [comment]
this sentence has been removed

**Comment by fmichonneau** [comment]
actually, it was in index.Rmd. I reworded to keep the reference to the CRAN website on how to uninstall old version, but made it optional
