### ISSUE TITLE
Provide guidelines for better managing package library 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#240]
A common reason people don't want to upgrade their R version, is that they need to reinstall all their packages afterwards.

There are several workarounds this issue, but they vary across OSes and can be a little technical, but it seems that having a guide somewhere that explains strategies to keep your packages across upgrades would be useful to our learners and the general public.

This is not urgent though, and should be addressed after the April lesson release.

(tangentially related to #234)

**Comment by Pakillo** [comment]
I saw just today that updateR will probably merge with installr very soon: https://github.com/AndreaCirilloAC/updateR/issues/10. Hence, installr will probably be a good cross-platform option to easily update R and all packages (I've been using it in the last couple of years and works nice)

**Comment by maurolepore** [comment]
This blog post shows how to [UPDATE R, RSTUDIO AND R PACKAGES](https://fgeo.netlify.com/2018/02/08/2018-02-08-update-r-rstudio-and-r-packages/), all from inside RStudio. Today, the function `updater()` lives in the __installr__ package, and lets the user decide if she wants to update the packages or not.

SHOULD I UPDATE ALL MY R PACKAGES FREQUENTLY? YES/NO? WHY? 
The answer is: Almost always yes; because not updating generally causes more trouble than updating -- see [this blog post](https://fgeo.netlify.com/2018/03/06/2018-03-06-should-i-update-all-my-r-packages-frequently-yes-no-why/).

![](https://i.imgur.com/BpCCkMO.png)

**Comment by Teebusch** [comment]
Given that this is a course for novices,  I think it is enough to recommend to 

> use the "Update" button in the RStudio packages panel every once in a while and occasionally check for new R versions on the [R project](https://www.r-project.org/) website. 

[`{intallr}`](https://github.com/talgalili/installr/) only works on Windows. So it is no a good cross-plattform option. It sure is convenient, but it only simplifies a process  that is already fairly simple to begin with:

- Updating packages through the package panel is easy enough.
- In my experience R doesn't need to be updated frequently since major changes are rare. 
- `installr`'s option to copy packages to the new version is a nice feature, but I prefer to use R version updates to "weed out" packages that I'm no longer using.
- In my experience, dependency/version conflicts when updating packages are extremely rare in R. Breaking changes in major packages are handled quite well, with warnings about soon-to-be deprecated functions being given long in advance.
- RStudio will notify the user of new RStudio versions automatically and the update process is fairly straightforward.

**Comment by Teebusch** [comment]
I believe the best way to manage package libraries is now to use `{renv}` + Git to keep a project-specific library with specific version numbers in a `.lock` file. renv allows you to use old package versions for old projects and newer versions for newer projects. If a package update breaks your code, renv allows you to roll back your project-specific package library. 

Anyways, I wonder if this whole topic is too advanced for the intended audience? 

Perhaps we should simply add a note to the [Preparations > Update R](https://datacarpentry.org/R-ecology-lesson/index.html#Update_R_and_RStudio) section, like 

>  You can check for new package version in the package panel in RStudio. There are also tools like installr that can help you with upgrading your R version. Generally, it is recommended to keep your R version and all packages up to date, because new versions bring improvements and bug fixes. Sometimes package updates might break your code. This can be very frustrating. To avoid this problem you can use a package called `renv`. However this is beyond the scope of this course.
