### ISSUE TITLE
Command for checking and setting working directories

### ISSUE THREAD

**Issue by shiva1387** [datacarpentry/R-ecology-lesson#321]
As a number of lessons begin with either downloading or saving the file, would it be worthwhile to discuss checking the current working directory (`getwd()`) or changing working directories (`setwd()`) by showing these commands in the "Getting set up" section of 00-before-we-start lesson?

Though this is handled in the RStudio's GUI, it might be useful to mention these commands as navigating to the correct working directory is one of the most common issues for learners.

**Comment by fmichonneau** [comment]
that sounds like a reasonable idea. Would you be willing to submit a PR to introduce `getwd()` and talk a little more about the concept of working directory?

**Comment by shiva1387** [comment]
Sure, i would add in a description and example of the usage and submit a pull request

**Comment by fmichonneau** [comment]
great, thank you!

**Comment by maurolepore** [comment]
The R community is moving away from using `setwd()` because it make your code not-reproducible. Instead, best practice is to use a project-oriented workflow, where the paths are relative to the project's root.

![](https://i.imgur.com/Y3fw2WA.png)

* [Discussion](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/)

* [Package __here__](https://krlmlr.github.io/here/)

* To force a project oriented workflow you can use [rstudio.cloud](https://rstudio.cloud/) (see also #380).
