### ISSUE TITLE
issues with data viz episode

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#334]
Submitted by email
_____

In the following episode (Data visualization with ggplot2) color is introduced only as a positive integer used to index into the current color palette colors().

The other ways of defining color are introduced only if you perform the 'challenge'.

I would suggest to mention the links to the following manuals which list all the colors used in R:
http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
http://research.stowers.org/mcm/efg/R/Color/Chart/ColorChart.pdf

In addition, when RColorBrewer package is used, default palettes include only 8-11 different colors.
To add tones to the existing palette can be done by writing the code:

library(RColorBrewer)
display.brewer.all()
# Classic palette YlGn with 4 colors
yellowgreen = brewer.pal(4, "YlGn")
# To add more tones to this palette:
yellowgreen = colorRampPalette(yellowgreen)(20)
# Plot as a piechart
pie(rep(1, length(yellowgreen)), col = yellowgreen)

**Comment by bbolker** [comment]
I would actually argue against this, for the following reasons:

- in the spirit of "only add something if you're going to take something else out to compensate", this feels like something that actually belongs in a challenge rather than the body of the lesson ...
- IMO if you are worried about adding more qualitative colors than are available in a colorbrewer palette you should think hard about your data visualization ... this many colors won't actually be distinguishable ... e.g. https://stackoverflow.com/questions/6075140/in-r-how-do-i-change-the-color-value-of-just-one-value-in-ggplot2s-scale-fill-b/6076605#6076605

**Comment by fmichonneau** [comment]
This issue doesn't seem essential for this lesson. Let's close it.
