### ISSUE TITLE
Assert statements

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#38]
We talk in the lessons about 'sanity checks' and making sure your data is what you expect it to be. Would it also be useful to introduce some introductory assert statements, like in the assert_that package?

https://github.com/hadley/assertthat

**Comment by karthik** [comment]
Hi Tracy,
Nice idea. There is no need to use `assertthat` directly since that is aimed at mostly testing code rather than data. I began a _unit testing for data_ package two years ago (testdat) and a couple of others have expanded on it for a more finished product.

1. One is `assertr`. I like this had spoke with the author about contributing it to rOpenSci's suite. It'll be there soon. We also had him on our community call last week. https://github.com/tonyfischetti/assertr

2. ENSURER: http://www.r-statistics.com/2014/11/the-ensurer-package-validation-inside-pipes/
By the guy who wrote pipes in R.

Both are good. I don't know where we would have time to fit this in so the lessons will need to be tightened up a bit.

**Comment by fmichonneau** [comment]
I think it'd be nice to mention **`assertr`** for instance in the context of the date conversion that is producing NAs

**Comment by maurolepore** [comment]
@karthik, 

It's been a while since your comment. Is __assertr__ up to date? I haven't tried it. What I did try is __assertive__ and -- for the purposes discussed here -- I think it is good: It gives lots of assertions and informative messages. It's downside is that it is substantially slow, so I no longer use it to build packages.

**Comment by anacost** [comment]
Assertions are out of the scope of this lesson. Therefore, I will close this issue.
