### ISSUE TITLE
introducing read.csv() before read.table()

### ISSUE THREAD

**Issue by eoziolor** [datacarpentry/R-ecology-lesson#391]
Hi,

I want to start with letting you know I think this is a fantastic lesson => this is a relatively minor question about the specific reason for why read.csv is introduced in the main text, while read.table is introduced in a side note. I think that there is an advantage of using read.table:

1) it introduces the idea of the header and tracking whether you do or don't have one in your data
2) it is more generic function with sep as a sub-option that can read multiple data types.
3) the fact that it is more verbose may allow people to see the versatility of loading variable data types

So my suggestion here is to move read.table to the example and introduce read.csv as a Note about a shortcut to load specific .csv data.

I know this may be just stylistic, but I thought it may give a little more weight on understanding how to load various data, which may be of interest to the diverse audience of the data carpentry workshops.

Thanks.

-Elias

**Comment by fmichonneau** [comment]
Thanks for your suggestion @eoziolor! I understand your point of view, and I'm a little bit on the fence on this because I see its value. To me, given our time constraints, I think that focusing on read.csv/read_csv makes the most sense. We want our learners to focus on best practices, including generating files that can be easily and widely read in, such as CSV. I wouldn't want our workshop participants to think they can save files in some _ad hoc_ format because R will let them read it. @aurielfournier @mondorescue @anacost what do you tihnk?

**Comment by anacost** [comment]
Hi, I agree that we should focus on best practices. I do not agree with reducing read.csv to a Note about csv files. 
"Excel is a common-format data storage program. An easy way to load such data into R is to save it as a csv (comma separated value) file and then use the read.csv() function to load it" (James, Witten, Hastie, Tibshirani, An Introduction to Statistical Learning with Application in R, Springer). 

read.table would be used in a text file, which should be previously opened in a standard text editor before loaded to R. 
Both functions are presented in the book (James, Witten, Hastie, Tibshirani, An Introduction to Statistical Learning with Application in R, Springer), but read.csv is the one used to load the data, finally.

**Comment by mondorescue** [comment]
I agree with @fmichonneau and @anacost . Since we expose students to **.csv** files, I think it is best to highlight `read.csv()` or `read_csv()` for consistency and best practices. I also think `read.table()` is for something outside the scope of the types of audiences (i.e. new programmers, folks with little or no computing background) that the Carpentry lessons, in general, aim to address. Therefore, `read.table()` in the side note seems appropriate to me.

**Comment by xpan1** [comment]
Hi,  I do agree @fmichonneau @anacost and @mondorescue. There are many different function of loading data in R, like, read.table(), read.csv(), read.delim(), read.csv2(), read.delim2() and so on. They all can be used for reading data in R, but there are small differences between them. Since this lecture is for introduce basic R commands for reading data and help the learners have the idea how to read the data, and also the data we provide is CSV files, in order to give students best practice, I think read.csv() is reasonable to show up in the main text and the read.table() is in the notes.

**Comment by ewallace** [comment]
I taught R for ecology this week and we had huge problems with read.csv vs read_csv. In lesson 02-starting-with-data some students used read_csv (instead of read.csv) and subsequent commands didn't work. Then, in 03-dplyr.html some students used read.csv (instead of read_csv) and likewise ran into problems.

I never use read.csv now myself, I load data exclusively with read_csv, read_excel, and so on.

Given all this, why not **only introduce readr/readxl functions**, and avoid the confusion? I don't see why it helps to introduce new users to superseded functions, it seems like needless complexity.

Apart from that the lesson went very well with great feedback from students, I appreciate how carefully put together the material is!

**Comment by mondorescue** [comment]
Working on adopting tidyverse concepts into the lessons, see tidyverse-first branch. Some of the issues presented has been addressed with #469 and will continue to be addressed as the lesson is updated in the tidyverse-first branch.
