### ISSUE TITLE
Suggestion to use mapping=aes(...) in ggplot section.

### ISSUE THREAD

**Issue by pfh** [datacarpentry/R-ecology-lesson#421]
(This issue submitted as part of my instructor training checkout.)

Introducing ggplot syntax, the template given is:

`ggplot(data = <DATA>, mapping = aes(<MAPPINGS>)) +  <GEOM_FUNCTION>()`

(Note: this should be enclosed in ` ``` ``` ` in order to render to html correctly.)

However when R code is given, the `mapping = ` is dropped:

`ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length))`

This will work, but it is very unusual to give a positional argument after a named argument (Python forbids this entirely, but it seems to work in R). This seems likely to cause confusion, as the `aes` function is already somewhat mysterious.

**Comment by aurielfournier** [comment]
Hello @pfh thanks for opening this issue.

Coming from python, a language I'm not fluent in by a long shot, that may seem odd, but is quite common in R, and we are using the mapping= to help guide the verbal description of the code, when explaining what `aes()` actually does.

Quite frequently the mapping= argument label is not used when folks are actually writing ggplot code, and so we want the learners to be comfortable seeing it as a positional argument, since many of the examples they will find online are written this way. 

If you think we could improve the explanation of this in our written lessons I would encourage you to submit a pull request.
