### ISSUE TITLE
Identifying interchangable notations in the lesson's code and brief reasoning

### ISSUE THREAD

**Issue by sabahzero** [datacarpentry/R-ecology-lesson#431]
One item I didn't realize until coding later on is that there are many inputs resulting in the same output. This could be a helpful sector of the lesson plan. 

For example, 
<- can also be = 
!is.na() can also be == FALSE or == TRUE or == 'quantity'

Spending 15-20 minutes pointing these out in the lesson plan, perhaps in the "Intro to R" section, and pointing out some quick linked references for students to further investigate in their own time may improve their foundational understanding of R and critical thinking of the lesson overall.

**Comment by aurielfournier** [comment]
Hello @sul-hasan thanks for opening an issue. 

We do cover different assignment operators in our first lesson in the R Ecology lesson set. 

We also cover `is.na()` in the subsetting section, and talk about boolean values as a whole as apart of subsetting data.

Is there something more specific then that you think would be important to add?

**Comment by sul-hasan** [comment]
Aah, I see that now! Thank you for pointing that out.

How about including another Challenge after "Intro to R > Functions and their arguments", though it may be too complex as an introductory exercise?

Q: What script mimics the same function as sqrt()?
A: x^0.5, where x is any positive number
Q: How might you write this as a function such that the output is the same as sqrt()?
squareroot=function(x) {
  x^0.5
  }
squareroot(x) = sqrt(x)

**Comment by aurielfournier** [comment]
Another challenge would be a great addition. Would you be willing to submit that as a pull request?

**Comment by sul-hasan** [comment]
Definitely! I'm a bit new to the GitHub pull request process and was [reading a bit](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request) about it, but am still unsure. I'm interested in knowing how to do this, possible to be walked through it for adding the challenge?

**Comment by fmichonneau** [comment]
The instructions you listed are relatively accurate. We don't have unit tests set up, so the 2nd steps is not relevant. We have a draft for instructions tailored to our repositories here: https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md

If you need additional help, feel free to join our Slack organization https://swc-slack-invite.herokuapp.com/ and ping me there.

**Comment by sabahzero** [comment]
Apologies that this took so long to get to - pull request complete!

**Comment by Teebusch** [comment]
Hi @sabahzero I am currently cleaning up the issue list and came across this one. I couldn't find your PR anywhere -- maybe something went wrong? Anyways, I also somewhat disagree with the suggestion and the proposed challenge (see my reasoning below). 

**Since this issue is 2.5 year old and abandoned, I will go ahead and close it now. I hope this is okay for everyone involved. However, please feel free to reopen if you disagree with me.**

---

About the issue: 

I think pointing out that the same goal can be achieved by different means in R is not worth spending 15-20 minutes of the introductory chapter on. It is important to stay focused, get the learner up and running, and not get lost in nuances. It's better to know _one_ way to solve a problem than to know multiple ways without really understanding them.
The interchangeability of `<-` and `=` is already mentioned briefly in the lesson:

> For historical reasons, you can also use = for assignments, but not in every context.

Learners will dive deeper into the interchangeability of notation later in the lesson, when we convert non-pipe syntax to pipe syntax. 

About the proposed challenges:

> Q: What script mimics the same function as sqrt()?
> A: x^0.5, where x is any positive number

I think this is more about the interchangeability of mathematical operations than about the interchangeability of code in R. It introduces a new operator `^` which adds more memory load. 

> Q: How might you write this as a function such that the output is the same as sqrt()?
> ```r
> squareroot = function(x) {
>     x^0.5
> }
>
> squareroot(x) = sqrt(x)
> ```

This requires introduction of the function syntax which is not yet part of the introductory chapter (and not introduced anywhere else in the course). I would prefer to keep it like this. Adding it would probably also require a discussion with the CAC.
The solution to the challenge also introduces `=` and `^` to demonstrate alternative ways for squaring and assigning. I think all this at the same time would just be overwhelming at that point in the lesson.
