### ISSUE TITLE
Verify number of data in R plot

### ISSUE THREAD

**Issue by MaySKTN** [datacarpentry/R-ecology-lesson#432]
Hi

I have 11872 data, plotted in R. I attached the data  that, I plotted in R. 
I would like to verify that 11872 data is plotted in the R graph. what function should i use? 

> library(ggplot2)
> library(tidyverse)
> library(lubridate)
> test <- read.csv('test_35.csv', colClasses = c('POSIXct', 'integer', 'integer'))

> ggplot(test, aes(x = localminute, meter_value)) +  geom_point() + ggtitle("meter value for dataID=35") +  scale_x_datetime(date_breaks = "10 days", date_labels = "%d/%m/%Y %H:%M%S", minor_breaks = NULL) + theme(axis.text.x = element_text(angle = 90, hjust = 1))  

The output data plot looks okay. 
![image](https://user-images.githubusercontent.com/39655493/40579131-8e57d0fa-6153-11e8-89af-8fc4a10a73ea.png)

But, when I filter the X-axis localminute (meaning plotting only data from 01-10-2015 to 31-10-2015, but I could not plot it, even X-axis is not displaying in the plot. I got the warning message "Removed 1495 rows containing missing values (geom_point)."  
When I opened the data  (in attached zip file), using notepad++, I found that there is no missing data. 

  >a <- ggplot(test %>%   filter(localminute >= ymd(20151001), localminute <= ymd(20151031)), aes(x = localminute, y = meter_value)) +  geom_point() + ggtitle("meter value for dataID=35") + scale_x_datetime(date_breaks = "10 days", date_labels = "%d/%m %Y %H:%M:%S", minor_breaks = NULL,limits = c(ymd_hm(201510010000), ymd_hm(201510022359))) +    theme(axis.text.x = element_text(angle = 90, hjust = 1))

> plot(a)

Warning message:
Removed 1495 rows containing missing values (geom_point). 

![image](https://user-images.githubusercontent.com/39655493/40579213-00afba90-6155-11e8-89ba-9ce8f78f9fcb.png)

[test_35.zip](https://github.com/datacarpentry/R-ecology-lesson/files/2041861/test_35.zip)

**Comment by callinSwitzer** [comment]
This issue has to do with the limits you have set on the x-axis. This argument, `limits = c(ymd_hm(201510010000), ymd_hm(201510022359))` sets the x-axis limits to be from "2015-10-01 UTC" to "2015-10-02 23:59:00 UTC".  I checked this on my computer by running the commands, 

`> ymd_hm(201510010000)`
[1] "2015-10-01 UTC"

`> ymd_hm(201510022359)`
[1] "2015-10-02 23:59:00 UTC"

The x-axis in your second plot is not displaying ticks or labels, because you specified `date_breaks = "10 days"`.  With the current limits, you are displaying two days worth of data, so you don't have any x-ticks or labels. 

The warning (Removed 1495 rows ....)  is occurring because the data you specified in this argument `test %>% filter(localminute >= ymd(20151001), localminute <= ymd(20151031))` contain points that are not plotted, because they are outside the your specified limits.  You can fix the warning and plot all the data by removing the argument, `limits = c(ymd_hm(201510010000), ymd_hm(201510022359))`, like this: 

`ggplot(test %>% filter(localminute >= ymd(20151001), 
                       localminute <= ymd(20151031)), 
       aes(x = localminute, y = meter_value)) + 
  geom_point() + ggtitle("meter value for dataID=35") + 
  scale_x_datetime(date_labels = "%d/%m %Y %H:%M:%S",
                   date_breaks = "10 days",
                   minor_breaks = NULL) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))`

![image](https://user-images.githubusercontent.com/7850472/40690891-1df48148-635e-11e8-98e6-59deab47def6.png)

To answer your question, 

> I would like to verify that 11872 data is plotted in the R graph. what function should i use?

You could use the following code to find out how many data points are in the dataframe: 

`test %>% nrow` will tell you the number of rows in the test dataframe.

`test %>% filter(localminute >= ymd(20151001), 
                localminute <= ymd(20151031)) %>% nrow`  will tell you how many rows are in the data you gave to ggplot in your second plot. 

`test %>% filter(localminute >= ymd(20151001), 
                 localminute <= ymd(20151031)) %>% filter(
localminute >= ymd_hm(201510010000), localminute <=ymd_hm(201510022359)) %>% nrow` will tell you how many points are shown in your second plot.  It is filtering your data twice -- first because of the data argument to ggplot, and second according to the x-axis limits.
