### ISSUE TITLE
smoothing transition between episodes

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#558]
Submitted by email from trainee - 

In terms of independence of the section inside the lesson and for practicality, I have a suggestion for the transition from the section "Manipulating, analyzing and exporting data with tidyverse", which ends creating a new data frame that is used in the next section "Data visualization with ggplot2". I would recommend to include a line of code at the beginning of the section "Data visualization with ggplot2" that will allow to extract that data from an online file. Is this way, if the lesson needed to be interrupted after finishing the section "Manipulating, analyzing and exporting data with tidyverse" (i.e. start the following section the next day), participants do not need to run the whole code from the previous section but instead they can download the data directly from internet.

**Comment by CaitlinBate** [comment]
I agree that this could be helpful! Another option, if this is the schedule of your workshop (and you know in advance), would be for the instructor to have the surveys_complete.csv file on a memory stick / dropbox etc. so that anyone who is having trouble finding their local version (or who maybe missed the previous episode) can participate in Data Visualization without back-tracking.

Perhaps this file and/or the code to create it could live in the instructors notes here https://datacarpentry.org/R-ecology-lesson/instructor-notes, not in the lesson itself (so learners do not automatically rely on the provided downloadable file). Either way it would be good for the instructor to have a shareable copy on hand, in some format - something I will think about when I teach this lesson.

**Comment by fmichonneau** [comment]
that's a good point. We'll have to think more about how to best include this link in the episode, but in the meantime, the file should be available for direct download from here: https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/data/portal_data_joined.csv?raw=true

**Comment by Teebusch** [comment]
somewhat related issue: #569

**Comment by tobyhodges** [comment]
Thanks everyone for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where appropriate.
