### ISSUE TITLE
Stress the (non)meaning of '.' in R compared to other languages (especially for the names of functions in the standard library)

### ISSUE THREAD

**Issue by mmesiti** [datacarpentry/R-ecology-lesson#591]
In other languages with C-like syntax and Python (and even in Fortran) the dot character has a peculiar meaning. 
R is pretty different in this regard, as dots are accepted in variable names and are largely used in the standard library. To a learner used to other languages, it seems that the 'as.*' functions can be part of module "as", implicitly loaded, that manages conversions between types. This is of course wrong. 

In the context of human languages, this situation is usually referred to as a "false friend" and such "false friends" are usually pointed out in language courses. The ["R-intro" bible on CRAN](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) state this in a way that is somewhat clearer (see section 1.8).

I find this situation sightly unsatisfactory, and I see two alternatives:
1. maybe there is a way to stress this out, maybe using a callout in the "Creating objects in R" section of the Intro episode (although there is already a callout about the "object vs variable" issue).
2. It could also be that this material is not the best for people who have some programming experience and such learners should just not be catered to and should instead be diverted to differently-flavoured material.

**Comment by James-S-Santangelo** [comment]
It seems this is already somewhat addressed in the `Creating objects in R` section of the lesson, which states: 

> It’s also best to avoid dots (.) within an object name as in `my.dataset`. There are many functions in R with dots in their names for historical reasons, but because dots have a special meaning in R (for methods) and other programming languages, it’s best to avoid them.

Are you suggesting this passage be expanded to specifically state that, unlike many other languages (e.g., Python), the '.' in `my.dataset` does not mean that `dataset` is an object exported from module `my`?

Of course, the '.' does have particular interpretation in R (e.g., in model formulae) but I think this would be beyond the scope of the R ecology lesson and this issue.

**Comment by mmesiti** [comment]
> Are you suggesting this passage be expanded to specifically state that, unlike many other languages (e.g., Python), the '.' in `my.dataset` does not mean that `dataset` is an object exported from module `my`?

Yes, that is  basically my quite unimaginative suggestion. 
Reasons for this are:
* I personally faced this issue when learning R from this material, so I believe someone may face the same issue.
* False friends should be evidenced in a learning environment
Reasons against this are:
* total novices which have no experience with python of C-like languages will not find this useful
* there is already a lot of content
* people who may benefit from such a clarification may not be the audience to this course? Honestly I find this to be the only compelling argument against expanding on this topic, but I am not sure this holds. Learning material from The Carpentries caters usually to novices or complete novices, but to me it seems that also somewhat experienced users that want to learn the basics of R will try this course, unless they are explicitly discouraged.

**Comment by James-S-Santangelo** [comment]
I think it could be worth adding a brief statement similar to the one that I wrote above, especially if it would help R novices familiar with other languages learn the current material. 

However, I would be weary of adding anything about 'false friends' since I think it would detract from the lesson material and is just another concept that would have to be explained in what may already be a pretty overwhelming lesson for some newcomers. 

Of course, it would be great to get some feedback from others as well, especially those who used this material when learning R and were coming from other languages. I learned R first so can't really comment on how confusing this might be, but agree it's worth discussing!

**Comment by mondorescue** [comment]
I acknowledge the potential confusion for those familiar with other languages, but as an introductory course _"to R designed for participants with no programming experience"_, I think the statement in **Creating objects in R** is sufficient for the target audience. However, I have no strong objection to adding a callout or a sentence considering individuals who have completed the Python Ecology lesson.

**Comment by Teebusch** [comment]
The topic of "dots in names" is addressed in "intro to R", ln. 72, in a way that is quite similar to what was suggested by @James-S-Santangelo:

>* It's best to avoid dots (`.`) within names. Many function names in R itself have them and dots also have a special meaning (methods) in R and other programming languages. To avoid confusion, don't include dots in names.

I think for a course primarily addressed at beginners this is sufficient.  Plus: In the same section there are also half a dozen other "rules" that learners have to process and remember.  I understand that there is a small group of learners who might benefit from a more detailed explanation, but it would come at the expense of the target audience who might get overwhelmed.

I will close this issue because it has been inactive for over 1.5 years and because I believe it is addressed sufficiently in the lesson. It seems that this @mondorescue agrees with me. However, if you disagree, please feel free to reopen @mmesiti , @James-S-Santangelo
