### ISSUE TITLE
Clarification on how to  use new script not console when working with R

### ISSUE THREAD

**Issue by fab927** [datacarpentry/R-ecology-lesson#605]
Please delete the text below before submitting your contribution. 

---

when working with R studio some people just use console to type their code and run it accordingly and am suggesting more clarification in part of the lesson -before-we-start. to add a line of how to start with a new script.
How : go to file menu, open new file and click R script or CTRL + SHIFT + N in widows 
i think it will be helpful to new learners
Thanks

**Comment by bridgeta** [comment]
I agree. It isn't well explained in the lesson that there should be a script file used. Most users like to replicate analyses either for checking on updated data or if they have lost their results to the ether...
Having a quick note about how to open and save scripts would be great.


> when working with R studio some people just use console to type their code and run it accordingly and am suggesting more clarification in part of the lesson -before-we-start. to add a line of how to start with a new script.
> How : go to file menu, open new file and click R script or CTRL + SHIFT + N in widows
> i think it will be helpful to new learners
> Thanks

**Comment by aekendig** [comment]
I'd like to help out with this issue for my instructor checkout if it still needs attention. It looks like this suggestion would fit in well at line 264 on the "Before we start" lesson. Here is the proposed text and the current text that would surround it. Let me know if this looks good, and I can submit a PR.

Current text: Because we want our code and workflow to be reproducible, it is better to type
the commands we want in the script editor, and save the script. This way, there
is a complete record of what we did, and anyone (including our future selves!)
can easily replicate the results on their computer.

Proposed text: To open a new script in the script editor, use the menu (File -> New File -> R Script) or the <kbd>`Ctrl`</kbd> + <kbd>`Shift`</kbd> + <kbd>`N`</kbd> shortcut (on Macs, <kbd>`Cmd`</kbd> + <kbd>`Shift`</kbd> + <kbd>`N`</kbd>).

Current text: RStudio allows you to execute commands directly from the script editor by using
the <kbd>`Ctrl`</kbd> + <kbd>`Enter`</kbd> shortcut (on Macs, <kbd>`Cmd`</kbd> +
<kbd>`Return`</kbd> will work, too)...

**Comment by fmichonneau** [comment]
Thanks for being willing to contribute to the lessons @aekendig!

I think this issue has partially been addressed with these changes: https://github.com/datacarpentry/R-ecology-lesson/pull/625/files

Does that cover what you had in mind or do you think more changes are needed?

**Comment by aekendig** [comment]
Ah yes, I missed that. I think that looks great. Thanks!

**Comment by fmichonneau** [comment]
You're welcome! Let us know if you have any other suggestions.
