### ISSUE TITLE
.org website layout issue. 

### ISSUE THREAD

**Issue by nrsc** [datacarpentry/R-ecology-lesson#614]
Whats up I just wanted to let you know your datacarpentry.org header overlaps the body of your document. I'm on firefox 77.0.
![dataCarp](https://user-images.githubusercontent.com/44142297/83587156-3de31a80-a503-11ea-8050-8bab913cfb3f.png)

**Comment by mondorescue** [comment]
@NRSC thank you for letting us know about this. I was able to replicate it when I resized the width of my web browser. I'm using Firefox 77.0.1.

**Comment by NRSC** [comment]
Hi. I apologize that the presentation of the issue was rather amateurish. I am self taught with git etc. Do you have any advice for me for next time I run into an issue?

**Comment by fmichonneau** [comment]
Hi @NRSC 

You brought up a good issue that needs to be resolved, so the issue may remain open.

In general, providing as much information as possible when describing an issue is the most helpful for maintainers. Thanks!

**Comment by Teebusch** [comment]
I can replicate this on Chrome Version 85.0.4183.121. This is due to the navbar wrapping on smaller screens. The sandwich menu only appears when the screen is <786 px wide, but wrapping is happening earlier, at > 1000 px screen width. 
One way to solve this in the CSS would be to use media queries to increase the `padding-top` of the content when the wrapping happens. See [this](https://stackoverflow.com/a/33463609/4620825) answer on StackOverflow. 

Besides covering the content, the wrapping also looks clunky, taking away more space then needed.

**Comment by tobyhodges** [comment]
The lesson was migrated to a new layout last year, so I am closing this.
