### ISSUE TITLE
Remove section about factors

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#616]
With R 4 not parsing character data as factors, learning about factors (at least the way it's currently introduced) isn't as important.

I suggest we remove this section entirely for the time being.

@datacarpentry/r-ecology-lesson-maintainers what are your thoughts on this?

**Comment by mondorescue** [comment]
I'm in favor of completely removing the section on factors since we are using `read_csv` to import the data.

**Comment by justinshaffer** [comment]
Not a maintainer but wanted to chime in.

Rather than remove this section, I think it would be helpful to re-tool it to address the change. For example, it could be re-focused to compare character vs. factor data, how to convert to factors, and include examples on when one might prefer one vs. the other. After introducing how to convert to factors, much of the existing material can still be used, as it focuses on factors.

I also agree with @mondorescue that the use of `read.csv` seems strange given the use of `read_csv` for the rest of the lesson. If folks agree that the use of factors with data imported using `read_csv` is still relevant, I suggest to eventually re-tool this section (Starting with Data) to use `read_csv` from the start.

**Comment by jebyrnes** [comment]
Could be useful to move to the data viz section to show how to order discrete things on the X-axis? Could even introduce forcats as a means of manipulation? Though that might be cognitively too much.

**Comment by fmichonneau** [comment]
addressed with #663
