### ISSUE TITLE
having 'extras' lessons 

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#63]
In the core lessons we can't teach everything. Often there are places where there could be more detail on a particular topic, or something that is an extension of a given topic. In those cases there are opportunities to have lessons that people can go through after the workshop on their own ('extras' like in SWC or On Your Owns (OYOs)). We have one recent PR that could fit that category. https://github.com/datacarpentry/R-ecology/pull/62

It would be nice to be able to point learners at these things, but there is then the added challenge in maintaining them. Are there thoughts on whether 'extras' should be included? Or other strategies on how they might be included or linked to? 

@fmichonneau @ethanwhite @karthik @kcranston @hlapp @karawoo @mkuzak @naupaka & others

**Comment by tracykteal** [comment]
One idea might be to have a list of OYOs that we'd like to have, and then just add those. If a new OYO is submitted outside that set, then there would have to be an explanation of how it fits in and why it's needed.

**Comment by naupaka** [comment]
My 2¢: It seems to me that while the core focus should remain on honing and polishing the core lesson set, or adapting it (esp. in the case of DC) to new knowledge domains beyond Ecology/Genomics, my sense is that there is certainly a place for these add-ons. I think an extras directory sounds good, and these additional lessons could be linked to from the bottom of the [main lessons website](http://www.datacarpentry.org/lessons/) in a section called 'Additional topics for self-study' or something. If the supplemental lessons remain relatively small and self-contained, then maintenance shouldn't be too much of a challenge. IME, maintenance burden goes up with a bunch of interlinked lessons that require a particular sequencing, since then changing in one place requires coordinated changes elsewhere. 

The other thing is thinking about whether or not these add-ons will necessarily be from one of the 'flavors' of DC. PR #62 uses the Ecology data, which means a Genomics course couldn't easily integrate it. Worth thinking about how to add additional lessons without too much fragmentation.

**Comment by ezcn** [comment]
Hi, 
the data set used for PR #62 is actually the one used in the R-ecology lesson of the DC Core. Perhaps extra lesson should stick to the data set they are written on?

**Comment by apawlik** [comment]
I like having the extras and I think what @naupaka suggests (small size of the lessons) is probably a good approach to maintenance. And I like the idea of @ezcn to stick to the same dataset. Helps the students to move from the lesson to OYO.

**Comment by fmichonneau** [comment]
I agree that having a few of these "extra" lessons would be helpful to learners who want to go a little deeper after a workshop, and for people who use the material online.

I agree with what has been said already about the fact the topics should be defined in advance (statistics, and shiny have been mentioned in issues previously, Rmarkdown, and integration of Git and RSutdio could be other good candidates). I am also wondering if these extra lessons should be in their own repository so they could be used across the main DC topics. This repository could also be where we store links to external resources for learning more about topics relevant to DC: R, Python, SQL, visualization, etc...

**Comment by fmichonneau** [comment]
this is a more general issue that we are working on addressing. Closing for now.
