### ISSUE TITLE
Add packages needed for lesson in setup instructions

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#68]
- dplyr
- ggplot2
- RSQLite

**Comment by k8hertweck** [comment]
A brief explanation of installation of R packages for non-sudo users would also be very helpful (comment from another instructor during a mentoring session)

**Comment by omsai** [comment]
It looks like it takes ~10 minutes to download, compile and install all 3 packages on UNIX systems, so it will certainly save a bit of workshop time to have those packages installed beforehand:

```sh
$ mv ~/R ~/R-orig
$ R
```

```R
install.packages("tictoc")
library(tictoc)
tic(); install.packages(c("dplyr", "ggplot2", "RSQLite")); toc()
#> ...
# 558.774 sec elapsed
#>
```

Looking at how the Software Carpentry R lessons handle installing packages, currently the lesson plan has the user install a package [right before using it](https://swcarpentry.github.io/r-novice-gapminder/13-dplyr/).

It sounds like we instead want to add a package section to the [index](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/index.md) page.  We could put something like:

---

## R Packages

Now that you have RStudio installed, start RStudio and at the bottom-right side you will see a pane with a few tabs: File, Plots, Packages, Help, Viewer.  Click on the "Packages" tab and then the "Install" button right underneath it.  In the window that opens, paste the following into the "Packages..." text box: `dplyr ggplot2 RSQLite` and click "OK".  You will see some text scrolling in your "Console" pane on the left side as the installation proceeds.  It can take several minutes, and when it completes the text will stop scrolling and end with the blue R prompt (`>`), and if you scroll through the "Packages" tab you will see entries for "dplyr", "ggplot2", and "RSQLite" listed in the "User Library" table.

---

What do you all think about advocating the graphical interface instead of using the R console and `install.packages()`?  The graphical way allows tab-completion and should be less error prone if e.g. the user is reading the R setup instructions on a projector or on another device and typing them into RStudio.

Using RStudio instead of a standalone R console, seems to come with conveniences where the user no longer needs to choose "[y/n]" to create or use a personal library, select a mirror, etc.

I'm having trouble trying to file this suggestion a PR.  It looks like [index.md](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/index.md) uses an HTML file `rSetup.html`, but I don't understand how that HTML file is being generated.  There is no Makefile rule to generate `rSetup.html`.  How do I modify `rSetup.html`?  I don't see this documented in `README.md` or `CONTRIBUTING.md`.

**Comment by fmichonneau** [comment]
discussion continues in #116
