### ISSUE TITLE
Minor suggestion to mention View() when presenting view()

### ISSUE THREAD

**Issue by paulapappalardo** [datacarpentry/R-ecology-lesson#685]
Hi. I wonder if in the section "Starting with data" it could be useful to mention that we are using *view* (lowercase v)  from the package tibble (under the umbrella of tidyverse), but that *View* (uppercase v) would also work to view data frames because is part of base R?. We talked earlier in the episode about the functions from specific packages versus the functions that come built into R, so it shouldn't be a new concept. I have always used *View* and just discovered *view* myself when looking through the  R-ecology-lesson :)

**Comment by mondorescue** [comment]
I think you have a good point, especially since `view()` in the **tibble** package is considered *experimental* by Müller, et al. Would you be willing to provide a suggested edit (i.e. Pull Request) to the text?

**Comment by paulapappalardo** [comment]
Sounds good, I will do a Pull Request (my first PR, so reading a bit to be sure I do not do something wrong). It seems I need to select or __base: main__ or __compare: main__, which one is the appropriate choice?

**Comment by mondorescue** [comment]
@paulapappalardo thanks for making the edits. Reviewing the changes, it seems that the note about `view()` vs `View()` may be better placed in the [Instructor Notes](https://github.com/datacarpentry/R-ecology-lesson/blob/main/instructor-notes.md) because the call out box is about `read_csv()`. Also (now thinking about it), `view()` vs `View()` isn't about importing data in R but rather about a "feature" of RStudio. What do you think?

**Comment by paulapappalardo** [comment]
That sounds good! And the instructor can decide if to mention it or at least have it in mind in case anybody asks.

**Comment by mondorescue** [comment]
@paulapappalardo Thanks for the contribution!
