### ISSUE TITLE
Clarify assignment vs. not in the filter/select section of the lesson

### ISSUE THREAD

**Issue by kaijagahm** [datacarpentry/R-ecology-lesson#716]
Hi maintainers,
One thing I love about this lesson is how it builds up to pipes by showing two alternatives: intermediate steps and nested functions. That's a great way to build intuition and also show what the advantages of pipes are.

However, I noticed that both of those other two ways show the subsetted dataset being assigned to a variable with the <- operator. But then all of the piped examples do not assign the dataset to anything--they just print the results to the console.

I have a couple thoughts/questions about this:
1) Have people already discussed this and decided that the way it is is best? If so, I'd be interested in the rationale. Apologies if this is a duplicate; I searched the closed issues and couldn't find anything that looked related.

2) If no to 1, then I think it would be good to show at least the first piped example getting assigned to something. I worry that learners might be confused if they're going along assigning their subsetted data to variables and then all of a sudden pipes are introduced without assignment. I could imagine getting the idea that with pipes, assignment is unnecessary––and then being really confused when the subsetting didn't "stick."

I can understand why, for brevity and demonstration purposes, we might want to leave most of the subsequent piped examples unsaved. But maybe we could just make a note after the first example, something like "in the other examples, we're not going to save the subsetted data to a variable."

3) Besides brevity, I can see that not assigning the results to a variable could be desirable because it allows the learner to immediately see the output in their console and observe that the data got subsetted. But that raises the question of whether we should also "show" the subsetted data in the non-piped examples. That's a little tricky because for the intermediate steps method, saving the subsetted data is inherently necessary. So maybe we'd want to type the name of the final product after the previous steps?

I guess a caveat at this point is that learners might already be super familiar with assignment, so they might intuitively understand why we're saving some results and not others. But I have a sense that at least some people might be confused.

What do others think? I'd be happy to make a PR for whatever change we decide to pursue here.

**Comment by Teebusch** [comment]
Hi, @kaijagahm thank you for raising this issue! 

There's one example, [right before the first pipe-related challenge](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html#Pipes) where the output of the pipe is assigned to a variable, mirroring the non-pipe version introduced before that. :

```r
surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

surveys_sml
```

It is commented with 

> If we want to create a new object with this smaller version of the data, we can assign it a new name:

Assignment is also done in the challenge for `mutate()` and `gather()`. You are right that for the rest of the examples in the chapter there is no assignment. I think it's mostly because it wouldn't be "useful" in the context (exploring the data, filtering, sorting and counting things...), and -- as you also point out -- because it's convenient to get the output in the console.
For the same reasons I'm not really in favor of adding more assignment to the pipe examples. I

I think, when I teach this I "intuitively" show the output of the non-pipe versions so learners can see what is happening and to make sure that it is working. Maybe explicitly adding that step to the lecture would be a good idea?

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here remain relevant to the redesigned lesson, linking to this thread where appropriate.
