### ISSUE TITLE
R for ecologist lesson 2: rename 'combine.csv' file

### ISSUE THREAD

**Issue by EmDeCoeur** [datacarpentry/R-ecology-lesson#729]
Looking through lesson 2, I clicked on the link to download the csv file (instead of downloading it via R) and moved it to the data_raw folder. It took me a couple of minutes to figure out why the rest of the code in the lesson was not working. The downloaded file is called 'combined.csv' and the file downloaded through R is renamed 'portal_data_joined.csv'. I was wondering whether they should be named the same, just to avoid confusion.  
Either rename 'combined.csv' in the figshare folder or write the code in the lesson as

download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data_raw/combined.csv")

Just a suggestion. I might be the only person who is doing silly things like downloading the file manually (for fun) instead of through R

**Comment by Gchism94** [comment]
I ran across this same issue... 
The options seem to either be changing the same as you suggested or using an example data set that is included in a package. 

I suggest using the "penguins" data set from the palmerpenguins package: https://allisonhorst.github.io/palmerpenguins/ 

Using penguins however would require the remaining lesson to be changed. In general however, it would make more sense to me to use example data sets for these lessons instead of downloading new data each time. This would require less lesson maintenance.
