### ISSUE TITLE
Adding more info about RStudio options in "Knowing your way around RStudio"

### ISSUE THREAD

**Issue by gsvidaurre** [datacarpentry/R-ecology-lesson#743]
These materials are really excellent, and I have a small suggestion that you should feel free to take or leave as you see fit. In the section "Knowing your way around RStudio" it might be beneficial to highlight the different options that users can change about the RStudio appearance in Tools > Global Options.

Some of these options available in "Global Options" are really helpful and if users know more about how to fiddle with these options then they might feel more comfortable in RStudio in the long-term. For instance, soft-wrapping lines of code can be really helpful, as can changing background/font colors and sizes (particularly for colorblind people or those with vision difficulties). One option I've found especially helpful when I've taught workshops is to have people change the pane layout so that the Source is on the upper left, the Console is on the upper right, and the Files/Plots/etc panel is on the bottom right. If the bottom panels are minimized, then there's more space allocated to the inputs (Source) and outputs (Console) that users can see on the screen.

**Comment by Teebusch** [comment]
Hi @gsvidaurre, thank you for the suggestion! I like your suggestion about highlighting options that could improve accessibility such as color scheme and font size. There are also some options for screen readers etc.
I personally also use the pane layout you suggest (code left, console right, both maximized), because it works well on small screens. I don't think I would suggest that everyone changes the layout, but it's probably worth mentioning that it is possible. 

I don't have time to draft a text for it, but if you (or someone else) want to, I would be happy to review a pull request.

**Comment by bmle** [comment]
Hi, just submitted a PR to describe that these accessibility options can be modified in the "Global Options" menu.

**Comment by fmichonneau** [comment]
closed with #781
