### ISSUE TITLE
Elements in "animals" object not consistent with function output

### ISSUE THREAD

**Issue by sbreitbart** [datacarpentry/R-ecology-lesson#768]
In the "Conditional subsetting" header, we see that 

`animals <- c("mouse", "rat", "dog", "cat", "cat")`

Yet when we run this code,
`animals %in% c("rat", "cat", "dog", "duck", "goat") `

our output suggests that "duck" and "goat" are in the animals vector while "rat" is not. Yet here's the output in the lesson:
`> [1] FALSE  TRUE  TRUE  TRUE  TRUE`

**Comment by fmichonneau** [comment]
Hi @sbreitbart,

the `%in%` looks in turn at each of the elements in the vector on the left and check whether they are found in the vector on the right side so:

- `mouse` is not in the vector on the right side which leads to `FALSE`
- `rat` is in the vector which leads to `TRUE`
- `dog`  is in the vector which leads to `TRUE`
- `cat` is in the vector which leads to `TRUE`
- and again `cat` is in the vector which leads to `TRUE`

so the output is consistent with the behavior of the function. Is there anything that we could clarify in the wording to explain better how this function works?

**Comment by Teebusch** [comment]
Part of the confusion may be because both vectors have the same length. If we make one vector shorter, it might be easier to understand what's going on, because the result will have the same length as `animals` but a different length than the other vector.

we could remove rat or dog from the animals vector, I suppose, because they demonstrate the same thing (an element that exists in the other vector). If we want a greater difference in length, we could remove dog from both and add two new animals to the other vector (how about `bird` and `fish` 🐦  ).

**Comment by sbreitbart** [comment]
Ah! Thanks for clarifying. I agree that making the vectors different lengths would be helpful, as would adding different animals to the other vector (like bird and fish!)

**Comment by fmichonneau** [comment]
Thanks for the suggestion! I added :bird: and :fish: to the vector we compare `animals` against.
