### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/R-ecology-lesson#786]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by Teebusch** [comment]
I think this is one of the issues that will be solved by the new lesson template. I suggest to put it on hold until then ("wait" label added).

(Possibly related to  #612)

**Comment by zkamvar** [comment]
Note: at the moment, we don't have jump links for every heading; only the sections enumerated in the sidebar because I want to make sure that we implement them in an accessible manner: https://github.com/carpentries/sandpaper/issues/285


That being said, once the lesson is transitioned to the workbench, the update will happen automatically. 

Another caveat to this particular issue: this was initially raised after a maintainer meeting where @annajiat noted that some lessons our out of date with other lessons and I asked him to tag me in the lessons that needed updating so that I have a list of lessons that I could get around to (as the process can take anywhere from 2 to 15 minutes per lesson, depending on merge conflicts). This lesson is an exception because it does not use the same styling as other lessons, so it can not be updated the same way.

**Comment by tobyhodges** [comment]
This was addressed when the lesson migrated to use the Workbench infrastructure.
