### ISSUE TITLE
Lesson Contribution -- Print argument n, being ignored by R?

### ISSUE THREAD

**Issue by GOnormandie** [datacarpentry/R-ecology-lesson#811]
In the Starting with Data Lesson, print(x, n) is repeatedly used, but when running it in my computer, the n argument seems to be ignored by R. For example, you say "If you wanted the first 50 rows, you could type print(surveys, n = 50)", but this prints all the rows. I tried with different numbers and it still prints all the rows.

When looking at the documentation of the R base function print(), it does not have an argument n. Maybe it was removed in a recent update?

Thank you!

**Comment by dalexis1995** [comment]
Hi, I am using R version 4.1.2, I run the code `print(surveys, n=50)` and it showed me the first 50 rows. I change it to several numbers and it is working fine for me. However, if you use `head(surveys, n=X)`, where X represents any number, it will only print the first rows but it will extract the information of the X number of rows. Could you provide the R version you are using? 

Thank you!

**Comment by Normandie-GO** [comment]
Hello Daniel!

I am using version 4.2.0.

Maybe is that?

Thanks for your quick response.

Enviado desde mi Samsung Mobile de Claro
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dalexis1995** [comment]
Hi! I think the version is not the issue, I tried and it worked fine. In order to use the function `print(surveys, n = X)`, we have to load the data using the function `read_csv` that comes within the `tidyverse` package so the data is stored as a `tibble`. If we use `read.csv` from the `utils` package it will not work correctly, since the data will be stored as a 'dataframe'.

Let me know if it worked.
