### ISSUE TITLE
Challenges from dplyr and ggplot should be included in the handout

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#94]
The handout (the chunks that have `purl = TRUE`) doesn't include everything it should. Especially the challenges from the dplyr and ggplot2 lessons are missing.

**Comment by btmoyers** [comment]
I've addressed this issue in pull request #132. I'm curious as to the reasoning behind what is and what is not included in the handout. With both the dplyr and ggplot2 lessons, the challenges mostly didn't include R code. Is the reason to include the challenge text just so that learners will have a script to start from when working on the challenges?

**Comment by fmichonneau** [comment]
Learning the syntax at the same time as the concepts is challenging for learners who have never programmed before. The handout tries to make this easier by providing relevant pieces of code so learners can focus on the concepts rather than the syntax. Thanks again for doing this!
